language: go

go:
  - 1.2.2
  - 1.3
  - tip

services:
  - postgres

before_script:
  - go get github.com/lib/pq
  - go get github.com/coopernurse/gorp

install:
  - go get -d -v ./... && go build -v .